const ActionTypes = {
  SET_SEARCH_QUERIES: 'SET_SEARCH_QUERIES',
  SET_VENUES: 'SET_VENUES',
  SELECTED_VENUE: 'SELECTED_VENUE',
  REMOVE_SELECTED_VENUE: 'REMOVE_SELECTED_VENUE',
};
export default ActionTypes;
